blog/urls.py
from django.urls import re_path, include
from . import views


app_name = 'blog'


urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^post_new/$', views.post_new, name="post_new"),
    re_path(r'^post_detail/(?P<pk>\d+)/', views.post_detail, name='post_detail'),
    re_path(r'^post_delete/(?P<pk>\d+)/', views.post_delete, name='post_delete'),
    re_path(r'^post_edit/(?P<pk>\d+)/', views.post_edit, name='post_edit'),

    re_path(r'^api/', include('blog.api.urls', namespace='blog_api')),
]

djangotest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse


def main(request):
    return HttpResponse('<h1>Hello</h1>')


urlpatterns = [
    path('', main, name='main'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('image/', include('image.urls', namespace='image')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import re_path
from . import views

app_name = 'users'


urlpatterns = [
    re_path(r'^profile/$', views.user_profile, name='user_profile'),
    re_path(r'^logout/$',views.logout_view, name='logout'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^signup/$', views.sign_up, name='sign_up'),
    re_path(r'^email_checker/$', views.email_checker, name='email_checker'),
]

djangotest/templates/layout.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static './style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

</head>
<body>
{% if messages %}
    <div class="container-fluid">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-warning">
                    {{ message }}
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success">
                    {{ message }} - {{ request.user }} 님 반갑습니다
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
<nav class="navbar navbar-expand-lg nav-bar-light bg-light">
    <a class="navbar-brand" href="{% url 'blog:post_list' %}">Board </a>
    {% if category_title %}
        <span class="badge badge-pill badge-default">{{ category_title }}</span>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">Menu</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">
                    <span class="badge badge-pill badge-warning">게시판</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for ca in category_list %}
                    <a class="dropdown-item" href="{% url 'blog:post_list' %}?category={{ ca.title }}">{{ ca.title }}</a>
                  {% endfor %}
                </div>
            </li>
        </ul>
      <div id="newPostNoti" class="noti invisible" data-aos="fade-in">
      </div>
        <div class="inline my-2 my-lg-0">
            {% if user.is_authenticated %}
                <a href="{% url 'users:user_profile' %}" style="text-decoration: none;">
                    <button class="btn btn-default btn-sm">Profile</button>
                </a>
                <a href="{% url 'users:logout' %}">
                    <button class="btn btn-warning btn-sm">로그아웃</button>
                </a>
            {% else %}
                <button id="myLoginBtn" class="btn btn-default btn-sm">로그인</button>
                <button id="myJoinBtn" class="btn btn-primary btn-sm">회원가입</button>
            {% endif %}
        </div>
    </div>
</nav>
<br><br>
{% block content %}
{% endblock %}
<script src="{% static './jquery-3.3.1.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>


{#로그인 모달#}
<div id="loginView" class="hiddenModal" style="display: none">
    <div class="login-modal-content">
        <h1>로그인</h1>
        <form method="POST" action="{% url 'users:login' %}">
            <div class="form-group">
                {% csrf_token %}
                {{ login_form }}
            </div>
            <input type="submit" class="btn btn-primary btn-sm btn-block" value="로그인">
        </form>
    </div>
</div>

{#회원가입 모달#}
{#joinEmail#}
{#joinId#}
{#joinNickname#}
{#password1#}
{#password2#}

<div id="joinView" class="hiddenModal" style="display: none;">
    <div class="login-modal-content">
        <h1>회원가입</h1>
        <form method="POST" action="{% url 'users:sign_up' %}#" id="joinForm">
            {% csrf_token %}
            <div class="form-group">
                {{ join_form.as_p }}
                <span class="small text-danger" style="display: none;" id="shortPass">비밀번호가 너무 짧습니다 (최소 8자)</span>
                <span class="small text-danger" style="display: none;" id="diffPass">비밀번호가 다릅니다!!</span>
            </div>
            <input type="submit" class="btn btn-primary btn-sm btn-block" value="회원가입">
        </form>
    </div>
</div>

<script>
    window.addEventListener('load', function () {
        let loginView = document.getElementById('loginView');
        let myLoginBtn = document.getElementById('myLoginBtn');

        let joinView = document.getElementById('joinView');
        let myJoinBtn = document.getElementById('myJoinBtn');

        {#콘솔창 에러 때문에 if 문 넣음 #}
        if (myLoginBtn) {
            myLoginBtn.addEventListener('click', function () {
                loginView.style.display = "block";
                document.getElementById('inputId').focus();
            })
        }
        if (myJoinBtn) {
            myJoinBtn.addEventListener('click', function () {
                joinView.style.display = "block";
                document.getElementById('joinEmail').focus();
            })
        }


        window.onclick = function (event) {
            if (event.target == loginView || event.target == joinView) {
                loginView.style.display = "none";
                joinView.style.display = "none";
            }
        }

        {#password 검사#}
        let password1 = document.getElementById('id_password1')
        let password2 = document.getElementById('id_password2')
        let joinForm = document.getElementById('joinForm')

        let submitCheck = false;

        joinForm.addEventListener('submit', function (e) {
            e.preventDefault()
            if (submitCheck) {
                joinForm.submit()
            }
            else {
                alert('입력사항을 확인해 주세요')
            }
        })

        {#패스워드 확인#}
        let diffPass = document.getElementById('diffPass')
        let shortPass = document.getElementById('shortPass')

        password1.addEventListener('keyup', function (e) {
            if (password1.value.length < 8) {
                shortPass.style.display = 'block'
            } else {
                shortPass.style.display = 'none'
            }
        })
        password2.addEventListener('keyup', function (e) {
            if (password1.value === password2.value) {
                submitCheck = true
                diffPass.style.display = 'none'
            } else {
                submitCheck = false
                diffPass.style.display = 'block'
            }
        })
    })
</script>
<script>
  const post_detail_url="{% url 'blog:post_detail' 1%}"
</script>
<script src="{% static 'js/websocket.js' %}" type="text/javascript"></script>
{% block javascript %}
{% endblock %}
 <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</body>
</html>