blog/urls.py
from django.urls import re_path, include
from . import views


app_name = 'blog'


urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^post_new/$', views.post_new, name="post_new"),
    re_path(r'^post_detail/(?P<pk>\d+)/', views.post_detail, name='post_detail'),
    re_path(r'^post_delete/(?P<pk>\d+)/', views.post_delete, name='post_delete'),
    re_path(r'^post_edit/(?P<pk>\d+)/', views.post_edit, name='post_edit'),

    re_path(r'^api/', include('blog.api.urls', namespace='blog_api')),
]

board/api/urls.py
from django.urls import re_path, path
from . import views

app_name = 'board'

urlpatterns = [
    re_path(r'^$', views.PostListAPIView.as_view(), name='post_list'),
    re_path(r'^(?P<pk>\d+)/$', views.PostDetailAPIView.as_view(), name='post_detail')
]

board/urls.py
from django.urls import re_path, include
from . import views


app_name = 'board'


urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^post_new/$', views.post_new, name="post_new"),
    re_path(r'^post_detail/(?P<pk>\d+)/', views.post_detail, name='post_detail'),
    re_path(r'^post_delete/(?P<pk>\d+)/', views.post_delete, name='post_delete'),
    re_path(r'^post_edit/(?P<pk>\d+)/', views.post_edit, name='post_edit'),

    re_path(r'^api/', include('board.api.urls', namespace='board_api')),
]

djangotest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse


def main(request):
    return HttpResponse('<h1>Hello</h1>')


urlpatterns = [
    path('', main, name='main'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('image/', include('image.urls', namespace='image')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.urls import reverse
from users.models import Profile
from comment.models import Comment


class Category(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Post(models.Model):

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering=['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=[self.pk])

    def short_date(self):
        return self.created_at.strftime("%y/%m/%d")

    @property
    def comments(self):
        qs = Comment.objects.filter_by_post(self)
        return qs

image/models.py
from django.db import models
from board.models import Post

# Create your models here.


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='image/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.photo)

board/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control form-control-sm',
                'id': 'title'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control form-control-sm',
                'rows': '10',
                'id': 'content',
            }),
        }
        labels = {
            "title": "제목",
            "content": "내용",
        }

board/api/views.py
from .serializers import PostSerializer, PostListSerializer
from rest_framework.generics import ListCreateAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework import status
from board.models import Post


class PostListAPIView(ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer

    def create(self, request, *args, **kwargs):
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

board/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


from .models import Post, Category
from .forms import PostForm
from .context_processors import board_custom_context
from .paginator import CustomPaginator, page_range_check

User = get_user_model()


def post_list(request):
    category = board_custom_context(request)['category_title']
    page = int(request.GET.get('page', 1))

    if category:
        try:
            category_q = Category.objects.get(title=category)
            qs = Post.objects.filter(category=category_q)
            p = CustomPaginator(qs, 10)
            qs = p.get_page(page)
            page_start, page_end = page_range_check(page, p.num_pages)
        except ObjectDoesNotExist:
            print('object does not exist!!!')
    else:
        category_q = Category.objects.get(title='free')
        qs = Post.objects.filter(category=category_q)
    return render(request, 'board/post_list.html',
                  {
                      "qs": qs,
                      "pages": p,
                      "prange": p.custom_page_range(int(page_start), int(page_end)),
                      "category_title": category_q,
                  })


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments
    page = int(request.GET.get('page', 1))
    category = post.category
    if category:
        category = Category.objects.get(title=category)
        qs = Post.objects.filter(category=category)
        p = CustomPaginator(qs, 10)
        qs = p.get_page(page)
        page_start, page_end = page_range_check(page, p.num_pages)


    return render(request, 'board/post_detail.html', {
        "post": post,
        "comments": comments,
        "category_title": post.category,
        "pages": p,
        "prange": p.custom_page_range(int(page_start), int(page_end)),
        "qs": qs,
    })


@login_required
def post_new(request):
    category = board_custom_context(request)['category_title']
    if category:
        try:
            category_q = Category.objects.get(title=category)
        except ObjectDoesNotExist:
            return redirect('board:post_list')

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.category = category_q
            user_obj = User.objects.get(username=request.user)
            post.profile = user_obj.profile
            post = form.save()
            return HttpResponseRedirect(reverse('board:post_detail', kwargs={'pk': post.pk}))
    else:
        form = PostForm()

    return render(request, 'board/post_form.html', {
        'form': form,
    })


@login_required
def post_delete(request, pk):
    if request.method == "POST":
        user_obj = User.objects.get(username=request.user)
        if user_obj == request.user:
            post = Post.objects.get(pk=pk)
            post.delete()
            return redirect('board:post_list')

    return redirect('board:post_detail', pk)


@login_required
def post_edit(request, pk):
    user_obj = get_object_or_404(User, pk=request.user.id)
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if user_obj == request.user:
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save()
                return redirect(post)
    form = PostForm(instance=post)
    return render(request, 'board/post_form.html', {
        'form': form,
        'post':post,
    })

board/templates/board/post_detail.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h4>[{{ post.category }}] {{ post.title }}</h4>
                <br>
                <p>
                    {% for image in post.image_set.all %}
                        <p>
                            <img src="{{ image.photo.url }}">
                        </p>
                    {% endfor %}
                </p>
                <p>
                    {{ post.content | linebreaks }}
                </p>
            <p>[댓글]<br>
               {% for comment in comments %}
                 {{ comment.content }} - {{ comment.created_at }}<br>
              {% endfor %}
            </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if request.user == post.profile.user %}
                <div class="ml-auto p-2 mb-5 mt-5">
                    <button class="btn btn-info btn-sm"
                            onclick=window.location.href="{% url 'board:post_edit' post.pk %}">수정
                    </button>
                    <button class="btn btn-warning btn-sm" id="post-delete">삭제
                    </button>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- 리스트 -->
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col" class="small">번호</th>
                <th scope="col" class="small" style="width:70%">제목</th>
                <th scope="col" class="small">작성자</th>
                <th scope="col" class="small">날짜</th>
            </tr>
            </thead>
            <tbody>
            {% for post in qs %}
                <tr>
                    <td class="small">{{ post.id }}</td>
                    <td class="small">
                        <a href="{% url 'board:post_detail' post.pk %}?category={{ category_title }}&page={{ qs.number }}">{{ post.title }}</a>
                    </td>
                    <td class="small">{{ post.profile.nickname }}</td>
                    <td class="small">{{ post.short_date }}</td>
                </tr>
            {% endfor %}
            {% if category_title %}
                <tr>
                    <td colspan="4">
                        <div class="d-flex flex-row-reverse mt-5 mb-1">
                            {% if user.is_authenticated %}
                                <a href="{% url 'board:post_new' %}?category={{ category_title }}">
                                    <button class="btn btn-sm btn-primary">
                                        글쓰기
                                    </button>
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

        <nav class="d-flex justify-content-center">
            <ul class="pagination pagination-sm">
                {% if qs.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?category={{ category_title }}&page={{ qs.previous_page_number }}">이전</a>
                    </li>
                {% endif %}
                {% for page_number in prange %}
                    <li class="page-item {% if qs.number == page_number %} active {% endif %} ">
                        <a class="page-link" href="?category={{ category_title }}&page={{ page_number }}"
                        >{{ page_number }}</a>
                    </li>
                {% endfor %}
                {% if qs.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?category={{ category_title }}&page={{ qs.next_page_number }}">다음</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#post-delete').on('click', function () {
                console.log('hi')
                if (confirm('제목 : {{ post.title }} \n정말 위 게시물을 삭제하시겠습니까?\n삭제된 게시물은 복구 할수없습니다.')) {
                    console.log('yes')
                    $.ajax({
                        type: 'POST',
                        url: '/board/post_delete/{{ post.pk }}/',
                        data: {
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function () {
                            window.location.href = "../../?category={{ post.category }}&page={{ qs.number }}"
                        }
                    })
                }
                else {
                    console.log('no')
                }
            })
        })
    </script>
{% endblock %}

board/templates/board/post_form.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <form method="post" action="" onsubmit="return getContent()">
            <div class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">작성</button>
            </div>
        </form>
    <div id="upload-image-list">

    </div>
        {% if post.image_set.all %}
            {% for image in post.image_set.all %}
                <img src="{{ image.photo.url }}" width="50"> {{ image }}<br>
            {% endfor %}
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            <img>
            <input type="file" onchange="previewFile()">
            <button class="btn btn-primary btn-sm" id="sendData" disabled>업로드</button>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        function getContent() {
            document.getElementById("upload-image-list").value = document.getElementById("divContent").innerHTML
        }

        function previewFile() {
            let preview = document.querySelector('img');
            let file = document.querySelector('input[type=file]').files[0];
            let reader = new FileReader();
            let button = document.getElementById('sendData')

            reader.onloadend = function () {
                preview.src = reader.result;
                preview.width = 100;
            }
            if (file) {
                reader.readAsDataURL(file)
                button.disabled = false;
            } else {
                preview.src = "";
            }
        }

        function getHostUrl(){
            return "http://" + window.location.host
        }
        document.getElementById('sendData').addEventListener('click', function (e) {
            e.preventDefault()
            let file = document.querySelector('input[type=file]').files[0];
            let datas = new FormData();
            {#let url = "http://localhost:8000"#}
            datas.append('photo', file)
            datas.append('post', '{{ post.id }}')
            $.ajax({
                type: "POST",
                {#contentType: 'multipart/form-data',#}
                {#dataType: 'json',#}
                url: getHostUrl() + '/image/upload/',
                data: datas,
                contentType: false,
                processData: false,
                success: function (data) {
                    let textarea = document.querySelector('textarea')
                    let img = document.createElement("img")
                    textarea.append(data.photo, img)
                    img.src = getHostUrl() + data.photo
                    console.log(textarea)
                    console.log(data.photo)
                }
            })
        })
    </script>
{% endblock %}

board/templates/board/post_list.html
{% extends 'layout.html' %}
{% block content %}
  <div class="container">
    <table class="table">
      <thead>
      <tr>
        <th scope="col" class="small" style="width:5%">번호</th>
        <th scope="col" class="small" style="width:70%">제목</th>
        <th scope="col" class="small">작성자</th>
        <th scope="col" class="small" style="width:1%">날짜</th>
      </tr>
      </thead>
      <tbody>
      {% for post in qs %}
        <tr>
          <td class="small">{{ post.id }}</td>
          <td class="small">
            <a href="{% url 'board:post_detail' post.pk %}?category={{ category_title }}&page={{ qs.number }}">{{ post.title }}</a>
          </td>
          <td class="small">{{ post.profile.nickname }}</td>
          <td class="small">{{ post.short_date }}</td>
        </tr>
      {% endfor %}
      {% if category_title %}
        <tr>
          <td colspan="4">
            <div class="d-flex flex-row-reverse mt-5 mb-1">
              {% if user.is_authenticated %}
                <a href="{% url 'board:post_new' %}?category={{ category_title }}">
                  <button class="btn btn-sm btn-primary">
                    글쓰기
                  </button>
                </a>
              {% endif %}
            </div>
          </td>
        </tr>
      {% endif %}
      </tbody>
    </table>
    <nav class="d-flex justify-content-center">
      <ul class="pagination pagination-sm">
        {% if qs.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?category={{ category_title }}&page={{ qs.previous_page_number }}">이전</a>
          </li>
        {% endif %}
        {% for page_number in prange %}
          <li class="page-item {% if qs.number == page_number %} active {% endif %} ">
            <a class="page-link" href="?category={{ category_title }}&page={{ page_number }}"
            >{{ page_number }}</a>
          </li>
        {% endfor %}
        {% if qs.has_next %}
          <li class="page-item">
            <a class="page-link" href="?category={{ category_title }}&page={{ qs.next_page_number }}">다음</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endblock %}